name: BTEAuditPlugin
version: '1.0'
main: mplugin.net.bTEAuditPlugin.BTEAuditPlugin
api-version: '1.21'
authors: [ Dillsteamgamer ]

commands:
  #Tester Commands
  TPToWorld:
    description: Teleports the player to the void world
    permission: BTEAuditPlugin.Tester
    default: op


  #Auditor Commands
  nextRegion:
    description: Teleport too the next region to be audited
    permission: BTEAuditPlugin.Auditor
    default: op

  markRegion:
    description: Marks the region status that is currently being reviewed
    permission: BTEAuditPlugin.Auditor
    default: op

  deleteRegion:
    description: Deletes the region file only when 2 unique (non executing) users mark the region as for deletion
    permission: BTEAuditPlugin.auditor
    default: op


  #Admin Commands
  nextDeleteRegion:
    description: TPs an Admin to the next world with 2 unique "Marked as for Deletion" authors
    permission: BTEAuditPlugin.deleteRegionFiles
    default: op


  #Other Commands
  regionStats:
    description: Provides the breakdown of all the regions in the audit
    permission: BTEAuditPlugin.Status
    default: op

  auditHelp:
    description: Displays a list of all commands and a description of what they do as well as their arguments
    permission: BTEAuditPlugin.auditHelp
    default: op


  #Other (Admin) Commands
  reloadDatabase:
    description: Updates the database with any new regions generated since last reload
    permission: BTEAuditPlugin.reloadDatabase
    default: op

  resetDatabase:
    description: Completely deletes the database, this should only ever be done in extreme scenarios, or a need of a new audit, must be followed by a new /reloadDatabase
    permission: BTEAuditPlugin.resetDatabase
    default: op

  reloadDatabaseWithQuickdelete:
    description: Updates the database with all regions, marking quickDelete for those that have never been inhabited
    permission: BTEAuditPlugin.reloadDatabase
    default: op